# Dependencies
markdown:         kramdown
highlighter:      rouge

kramdown:
  input:          GFM

# Permalinks
permalink:        pretty

# Setup
title:            Data Science for SAFS
description:      'Teaching the tools to get computers to do cool science'
url:              https://sr320.github.io/course-497-2018
baseurl:          /course-497-2018
email:            roberts.sbr@gmail.com
feedbackurl:      
author:
  name:           'Steven Roberts'
  url:            https://twitter.com/sr320

github:
  repo:           https://github.com/sr320/course-497-2018
  #               Be sure the 'Issues' feature is activated in 'Settings'
